### ISSUE TITLE
node builds need to be static

### ISSUE THREAD

**Issue by jeffgca** [robhawkes/node-extension#1]
If I try to run your build of node I get this error:

dyld: Library not loaded: /opt/local/lib/libssl.1.0.0.dylib
  Referenced from: /Users/jeff/code/jetpack/projects/node-jetpack/data/x86_64-gcc3/node
  Reason: image not found
Trace/BPT trap: 5

If you're going to distribute node in an extension, you'll need to build it statically.

**Comment by robhawkes** [comment]
It seems Node is built "mostly statically" apart from a few external libraries. Turns out libssl is one of them so I need to work out how to best bundle that in somehow. [I found this](http://groups.google.com/group/nodejs/browse_thread/thread/162d8a33bbc34b47/775ae2f986f4ac9c?lnk=gst&q=static+libssl#775ae2f986f4ac9c), but I'll keep looking for other solutions.

**Comment by robhawkes** [comment]
Ok, this is harder than I thought. There's really no straightforward documentation about how to compile a static build of libssl and link it into the Node.js executable.

Any ideas?

**Comment by robhawkes** [comment]
Still not sussed it out but I've removed SSL from Node entirely until I can work it out. Can you confirm that the latest build in this repo (6434ba1) doesn't give you any library errors?

**Comment by jeffgca** [comment]
A friend of mine works at joyent and is fluent in build systems, I'll ping him and report back.

**Comment by robhawkes** [comment]
Sweet, thanks!

**Comment by trentm** [comment]
said friend is just asking Ryan (Dahl). Ryan suggested that you should "use the gyp build" and pointed to:

https://github.com/joyent/node/blob/f44d0b90442d9a1dc7457924f827722fc3a7c440/node.gyp#L10

You should do a build with that 'node_use_system_openssl%' set to false.

"""
(./configure-gyp in v0.6 and ./configure in master build a file called options.gypi which contains usually sets that to true https://github.com/joyent/node/blob/a033261f3901c42498e7ac3f2372820f31f7d1e1/configure#L217-218
"""

I haven't looked too deeply at the ticket here to know if that is insufficient information. Hopefully enough to get going on.

**Comment by jeffgca** [comment]
Thanks man!

**Comment by robhawkes** [comment]
Wow, way to take this right to the top! Thanks guys, I'll take a look through those links and update this ticket with my progress.

**Comment by robhawkes** [comment]
Ok, so it looks like the gyp build did the trick. I've uploaded a new build to this repo (ef1c2d6) that was created on a Mac.

I'm not sure whether I needed to include the "libopenssl.a" and other files along with the Node executable, it's a few MB larger than the previous one so I assume they were baked-in. I'd appreciate it if someone can confirm that it works ok and doesn't give any library errors.

**Comment by jeffgca** [comment]
Works for me!

**Comment by robhawkes** [comment]
Wahoo! That's a promising sign then. Thanks for bringing this to my attention and helping me fix it, I'd not have noticed until too late otherwise.

Now to work out which platforms to build for and how to actually perform all those builds…

**Comment by trentm** [comment]
@robhawkes: Sounds like you are passed this, but you should NOT need to include the libopenssl.a file. That is used for static linking into the node binary, but once it is linked in you don't need to distribute that file.

Use `ldd node` (or `otool -L node` on Mac) to list dynamic links in a binary. If that list does not include "libopenssl" then you are good to go.
